import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}><div className="flex justify-center items-center"><div className="w-[85%] h-screen">{children}</div></div></body>
      {/* <body className={inter.className}><div className="w-full h-screen">{children}</div></body> */}
    </html>
  );
}
